server:
  port: 8082

spring:
  application:
    name: order
  datasource:
    url: jdbc:h2:mem:ordersdb
    driverClassName: org.h2.Driver
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    bootstrap-servers: localhost:9092

kafka.order-event-topic: orders