server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: users
          uri: http://localhost:8081/
          predicates:
            - Path=/user/**
        - id: orders
          uri: http://localhost:8082/
          predicates:
            - Path=/order/**
    consul:
      enabled: true
      discovery:
        # Get only services that are passing the health check
        query-passing: true