server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        # Not needed since we excluded the dependency
        enabled: false
    gateway:
      routes:
        - id: users
          uri: lb://user/
          predicates:
            - Path=/user/**
        - id: orders
          uri: lb://order/
          predicates:
            - Path=/order/**
        - id: statistics
          uri: lb://statistic/
          predicates:
            - Path=/statistic/**
    consul:
      enabled: true
      discovery:
        # Get only services that are passing the health check
        query-passing: true