server:
  port: 8083

spring:
  application:
    name: statistic
  datasource:
    url: jdbc:h2:mem:statisticsdb
    driverClassName: org.h2.Driver
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: app.1

kafka.order-event-topic: orders